### ISSUE TITLE
Add this app to Yunohost's catalog ?

### ISSUE THREAD

**Issue by alexAubin** [YunoHost-Apps/etherpad_ynh#17]
(c.f. https://forum.yunohost.org/t/interrogations-diagnostique-suite-a-maj/18092 )

I don't know much about the difference between this one and etherpads_mypad in terms of feature tho

**Comment by ericgaspar** [comment]
The idea of resurrecting this package was to have Etherpad as light as possible (without plugins and with Redis as database).
The Redis helper still lacks some features such as backup/restore database...
